name: first_dependency
version: 1.0.0
dependencies:
  analyzer: ">=0.26.1+3 <0.28.0"
  barback: "^0.15.0"
  browser: ">=0.10.0 <0.11.0"
  browser_detect: "^1.0.3"
  matcher: ">=0.11.0 <0.13.0"
  quiver: ">=0.21.4 <0.23.0"
  rate_limit: "^0.1.0"
  react: "^1.0.0"
  source_span: "^1.2.0"
  tuple: ">=0.4.0 <2.0.0"
  w_flux: "^2.2.0"
  yaml: "^2.1.8"

dev_dependencies:
  args: "^0.13.4"
  coverage: "^0.7.2"
  dart_dev: "^1.0.5"
  dart_to_js_script_rewriter: "^1.0.1"
  fluri: "^1.1.1"
  markdown: "^0.7.1+2"
  mockito: "^0.11.0"
  mustache: "^0.2.3"
  path: "^1.3.6"
  sass: "^0.4.2"
  test: "^0.12.6+2"
  webdriver: "^1.0.0"
  xml: "^2.4.2"
